### ISSUE TITLE
Biblioteca yed não encontrada na compilação - Repositório privado

### ISSUE THREAD

**Issue by rafaelchagasb** [opensingular/singular-core#1]
A biblioteca yed não está disponível no repositório central e por isso não é possível compilar o projeto. Possivelmente ela deve estar dentro de um repositório privado que não é acesso externamente.
groupId: y.ed
artifactId: yfiles
version: 3.0.0.1

A biblioteca pode ser configurada com o escopo system e disponibilizada a partir de uma pasta lib do projeto. Outra solução é adicionar um repositório público no pom.xml que contenha a biblioteca.

**Comment by viniciusuriel** [comment]
Obrigado pela observação Rafael. Vou abrir uma issue para a correção do problema.

**Comment by viniciusuriel** [comment]
Corrigido na versão 1.5.4
